name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04   # 固定系统版本，避免系统依赖差异

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers and system deps
        run: python -m playwright install --with-deps

      - name: Run API tests
        run: pytest tests/api -q

      # 生成 HTML 报告；成功/失败都生成
      - name: Run UI tests (Playwright) with HTML report
        run: |
          mkdir -p playwright-report
          pytest tests/ui -q \
            --tracing=retain-on-failure \
            --screenshot=only-on-failure \
            --video=off \
            --html=playwright-report/index.html --self-contained-html

      # 调试：列出要上传的目录（遇到不存在也不报错）
      - name: List report dirs (debug)
        if: always()
        run: |
          echo "== ls playwright-report =="
          ls -Rl playwright-report || true
          echo "== ls test-results =="
          ls -Rl test-results || true

      # 上传报告与失败产物（注意：这里不能写注释在路径行里）
      - name: Upload Playwright report & traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          # 用通配符；playwright-report 一定存在；test-results 只有失败时出现
          path: |
            playwright-report/**
            test-results/**
          if-no-files-found: warn
          retention-days: 7
