name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Pages 需要的权限（很重要）
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04   # 固定 22.04（Playwright 依赖更稳定）
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers and system deps
        run: python -m playwright install --with-deps

      # 运行 API & UI（你的 pytest.ini 里已经配置了 HTML 报告输出到 playwright-report/index.html）
      - name: Run API tests
        run: pytest tests/api -q

      - name: Run UI tests (Playwright) with HTML report
        run: pytest tests/ui -q

      # 上传 Artifact（保底，失败也上传）
      - name: Upload Playwright report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          if-no-files-found: error
          retention-days: 7

      # 上传 Pages 工件（把整个 HTML 报告目录作为站点内容）
      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4
