name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Tokyo     # ← 让构建机按日本时区运行

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Show current time (debug)
        run: |
          echo "System time:"
          date
          python - << 'PY'
          import datetime, time, os
          print("Python datetime.now():", datetime.datetime.now())
          print("TZ env:", os.environ.get("TZ"))
          print("time.tzname:", time.tzname)
          PY

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers and system deps
        run: python -m playwright install --with-deps

      - name: Run API tests
        run: pytest tests/api -q

      - name: Run UI tests (Playwright) with HTML report
        run: pytest tests/ui -q

      - name: Upload Playwright report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            ui-report.html
            test-results/

      # 生成并发布到 GitHub Pages（保持你现在的成功配置即可）
      - name: Prepare GitHub Pages content
        if: always()
        run: |
          mkdir -p gh-pages
          cp ui-report.html gh-pages/index.html || true
          [ -d test-results ] && cp -r test-results gh-pages/test-results || true

      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh-pages

      - name: Deploy to GitHub Pages
        if: always()
        uses: actions/deploy-pages@v4
