name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-22.04
    # 这行决定了是否在 job 卡片显示“直达链接”
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers and system deps
        run: python -m playwright install --with-deps

      - name: Run API tests
        run: pytest tests/api -q

      - name: Run UI tests (Playwright) + build HTML report
        run: |
          pytest tests/ui -q \
            --html=ui-report/index.html --self-contained-html

      - name: Upload Playwright report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ui-report/             # 这里面有 index.html
          if-no-files-found: warn
          retention-days: 7

      # 把 ui-report/ 打包成“待部署到 Pages 的工件”
      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: ui-report/

      # 真正发布到 GitHub Pages，并把 page_url 作为 outputs 回传
      - name: Deploy to GitHub Pages
        if: always()
        id: deploy
        uses: actions/deploy-pages@v4
